addSbtPlugin("io.gatling"     % "gatling-sbt"    % "4.19.1")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.12.0")
addSbtPlugin("com.github.sbt" % "sbt-git"        % "2.1.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.6.2")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"  % "2.4.4")
